import { Link } from "react-router-dom";
import {
  pageWrapper,
  pageTitleClass,
  bodyText,
  primaryBtn,
  section,
} from "../styles/common";

export default function Home() {
  return (
    <div className={pageWrapper}>
      {/* ── Hero ─────────────────────────────────────────────── */}
      <div className="text-center mb-12 py-20">
        <p className="text-[0.65rem] font-semibold text-[#0066cc] uppercase tracking-widest mb-3">
          AI-Powered Resume Analyzer
        </p>
        <h1 className={`${pageTitleClass} text-center mb-4 text-6xl`}>
          Optimize your resume.<br />Land your dream job.
        </h1>
        <p className={`${bodyText} text-center max-w-lg mx-auto mb-10 text-lg`}>
          Get instant AI-driven insights, ATS scores, and personalized suggestions to make your resume stand out to recruiters.
        </p>

        <div className="flex justify-center mt-8">
          <Link
            to="/upload"
            className={`${primaryBtn} px-10! py-4! text-lg! rounded-2xl! shadow-xl shadow-[#0066cc]/20 hover:scale-105 transition-transform`}
          >
            Analyze Resume →
          </Link>
        </div>
      </div>

      {/* ── Feature strip ─────────────────────────────────────── */}
      <div className={`${section} mt-16`}>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-px bg-[#e8e8ed] border border-[#e8e8ed] rounded-2xl overflow-hidden">
          {[
            { icon: "🎯", title: "ATS Scoring", desc: "See exactly how well you match any job posting." },
            { icon: "💡", title: "Smart Suggestions", desc: "Actionable tips generated by AI to strengthen your resume." },
            { icon: "🔍", title: "Skill Gap Analysis", desc: "Pinpoint missing keywords before you apply." },
          ].map((f, i) => (
            <div key={i} className="bg-[#f5f5f7] p-8 hover:bg-[#ebebf0] transition-colors duration-200">
              <div className="text-3xl mb-4">{f.icon}</div>
              <h3 className="text-base font-semibold text-[#1d1d1f] mb-2">{f.title}</h3>
              <p className={bodyText}>{f.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
